### ISSUE TITLE
0.470 pixscale for 90Prime

### ISSUE THREAD

**Issue by kaylanb** [legacysurvey/legacyzpts#1]
Since legacy_zeropoints was configured to reproduce Arjun's IDL code, it adopted the pixel scales therein which are 0.470 (not 0.455) for 90prime and 0.262 (not 0.260) for MzLS.
https://github.com/legacysurvey/legacypipe/blob/master/py/legacyccds/legacy_zeropoints.py#L1471

Changing these requires changing the SE/PSFex config files, see here:
https://github.com/legacysurvey/legacypipe-dir/issues/3
so these setting are kept for DR5.

**Comment by kaylanb** [comment]
Taking this off of DR6 punchlist

At last imaging call we talked about not changing these pixel scale numbers because of the development to include PSFex

**Comment by moustakas** [comment]
Does anyone have any insights into the relevance of this issue?  @dstndstn @mlandriau @djschlegel ?

**Comment by djschlegel** [comment]
Close and move issue to legacypipe product https://github.com/legacysurvey/legacypipe/issues/329
