### ISSUE TITLE
DR7: CCD S7

### ISSUE THREAD

**Issue by kaylanb** [legacysurvey/legacyzpts#10]
Need to compute a zeropoint for each amplifier (decam has 2 amplifiers). One is bad other is good. Give legacypipe/tractor the zpt from the good amplifier since tractor will not use pixels of the bad one

ideas
* split detected sources by ra,dec in region of amp A, vice versa amp B

Email chains
* "zeropoints for eBOSS DR5" on decals-chatter
* "Zero-points for CCD 31 (S7)" on decals-chatter.

**Comment by moustakas** [comment]
Does anyone have any insights into the relevance of this issue? @dstndstn @mlandriau @djschlegel @schlafly

**Comment by dstndstn** [comment]
I believe we copied the relevant code (to ignore half of S7) from
legacypipe to legacyzpts.
I think we can close this
