### ISSUE TITLE
DR6: remove zero'd columns and add ID from Gaia, PS1

### ISSUE THREAD

**Issue by kaylanb** [legacysurvey/legacyzpts#18]
After creating the first set of DR6 zeropoints files here
/global/cscratch1/sd/kaylanb/zpts_out/dr6/bok/BOK_CP/ 
/global/cscratch1/sd/kaylanb/zpts_out/dr6/mosaicz/MZLS_CP/ 
named 
"*-legacypipe.fits", "*-zpt.fits", "*-star-photom.fits", "*-star-astrom.fits"

There are 4 things that need to be fixed for the final DR6 zeropoints files
 1) Remove unneeded cols from _ccds_table and have different cols for the photom and astrom
tables
 2) fix bug in astrom table where ra,dec,x,y,gaia_ra,gaia_dec not added to stars table
 3) Additional stars table columns
 * _photom_
PS1_ID of match
	PS1_RA
	PS1_DEC
	PS1_Epoch (mean epoch if available)
	PS1_photometry (g/r/i/z/**y**)
        LS_epoch
	LS_filter
	LS_photometry (from tractor)
	LS_filename
	LS_CCD
  * _astrom_
Gaia_ID
	gaia_RA
	gaia_DEC
	Gaia_G
	Gaia_epoch
	LS_epoch
	LS_filter
	LS_photometry (from tractor)
	LS_filename
	LS_CCD
and a header card saying whether PS1-Gaia or PS1 was used from astormetry
 
4) Do we make an additinal photometry table containing the PS1-gaia photometry info? Less stars that the "photom" table but useful...?

**Comment by moustakas** [comment]
Does anyone have any insights into the relevance of this issue? @dstndstn @mlandriau @djschlegel @schlafly

**Comment by schlafly** [comment]
Dustin has addressed these in the new photom files.  We have all needed columns, and the files all have a consistent data model.  I don't really know whan item 1 refers to, but I do not think that it remains an issue.
