### ISSUE TITLE
Outlier photometric and astrometry offsets

### ISSUE THREAD

**Issue by kaylanb** [legacysurvey/legacyzpts#3]
In DR4 we threw out 5-10% of the CCDs because they had outlying astrometric or photometric offsets in Arjun's zeropoint file: "np.hypot(ccdrarms, ccddecrms) > 0.1 OR ccdphrms > 0.2". At the time legacy_zeropoints had many less outliers for the same CCDs, e.g. 
<img width="689" alt="offsets" src="https://user-images.githubusercontent.com/5062170/27660835-d35d6e96-5c0c-11e7-9610-0f16aa9060a1.png">
Is this still the case? Why are those outliers there? Are they okay to use in the DRs?

**Comment by kaylanb** [comment]
Taking off DR6 punchlist in interest of time

**Comment by moustakas** [comment]
Closing this stale issue.
