### ISSUE TITLE
DR8 MzLS failures that succeeded in DR6

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#31]
An example is:

k4m_171124_041246_ooi_zd_v1.fits.fz

Which failed during DR8 zeropointing with the message:

AttributeError: 'NoneType' object has no attribute 'patch’

See also:

https://desi.lbl.gov/mailman/private/decam-chatter/2019-February/008474.html

**Comment by ameisner** [comment]
The only other three examples that I found:

k4m_170127_091254_ooi_zd_v1.fits.fz
k4m_170426_050902_ooi_zd_v1.fits.fz
k4m_171008_093737_ooi_zd_v1.fits.fz

**Comment by djschlegel** [comment]
The listed files (and in fact all of the MOSAIC exposures) have completed the zero-point code for DR8 as of 9 April 2019.  Some of these cases may have been due to weird WCS in the image headers, see issue #41.  Closing this issue, should it re-surface we will track on the legacypipe product.
