### ISSUE TITLE
MzLS EXPNUM values that changed between DR6 and DR8

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#32]
Does anybody understand this? May be a DR6 issue rather than a DR8 issue. See also:

https://desi.lbl.gov/mailman/private/decam-chatter/2019-February/008474.html

"The first row of mzls_missing.fits is an image named k4m_151120_105223_ooi_zd_v1.fits.fz. There are 4 rows of the DR8 ccds-annotated file with this string in their IMAGE_FILENAME, and all have EXPNUM = 151120105223. On the other hand, in DR6’s ccds-annotated-mosaic-z.fits.gz, k4m_151120_105223_ooi_zd_v1.fits.fz has EXPNUM = 796249863."

**Comment by dstndstn** [comment]
int32(151120105223) = 796249863 !

**Comment by ameisner** [comment]
This is indeed the solution, so this issue ended up pertaining to a DR6 bug that has since been fixed.
