### ISSUE TITLE
effect of fpack'ed invvar values on spline sky generation

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#33]
Eddie pointed out that the fpack'ing of invvar images caused problems for the spline sky fitting:

https://desi.lbl.gov/mailman/private/decam-chatter/2019-February/008430.html

Not sure if this has been fixed? Is this even the right repo to be ticketing for this issue?

**Comment by moustakas** [comment]
Fixed by @dstndstn in https://github.com/legacysurvey/legacyzpts/commit/8c479f227b8a9eac202c3af8480171aa004d4362.
