### ISSUE TITLE
per-exposure output data model

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#34]
The current per-exposure output data model is fairly absurd. For each exposure, there are currently 3 very similar output files containing tables with one row per CCD. These 3 files should either be combined into one single table, or combined into one multi-extension FITS file per exposure.

There is a similar situation for the -astrom and -photom outputs. We should either combine these into one table, or write them out as a single multi-extension FITS file.

The above suggestions would take us from 5 output files per exposure to only 2, saving a lot of inodes. An even more extreme alternative would be to write the contents of the current 5 output files per exposure to one single multi-extension FITS file, reducing the number of output inodes by 5x.

**Comment by ameisner** [comment]
Also, there should be a directory structure for these outputs that doesn't involve putting all files into one giant flat directory.

**Comment by dstndstn** [comment]
in 0d83d8f, added a level of directory structure, and eliminated astrom and zpt outputs.
