### ISSUE TITLE
automate zeropoint sanity checks

### ISSUE THREAD

**Issue by ameisner** [legacysurvey/legacyzpts#35]
Some of the zeropoint sanity checks I've been doing could/should be automated. For example, checks for corrupt files and checks of uniqueness of (EXPNUM, CCDNAME) pairs in the merged CCD tables.

**Comment by ameisner** [comment]
I can contribute to this, but almost certainly not until after the commissioning instrument campaign is over several months from now.

**Comment by moustakas** [comment]
@schlafly @mlandriau @djschlegel  Do you know off-hand if there are situations where a CP-processed image ends up with anything other than 60 CCDs/HDUs (for DECam) and 4 CCDs/HDUs (for Mosaic and Bok)?

In other words, should the code fail if a given input image is "incomplete"?  Or can this happen during normal processing?

**Comment by schlafly** [comment]
> Do you know off-hand if there are situations where a CP-processed image ends up with anything other than 60 CCDs/HDUs (for DECam) and 4 CCDs/HDUs (for Mosaic and Bok)?

For DECam this happens.  At some point all 62 CCDs were working.  N30 and S30 failed at some point, and later N30 (I think) came back to life.  So in principle I think 60-62 CCDs could all be expected.

Not sure about the other systems.

**Comment by schlafly** [comment]
There was also a brief window of time with DECam where ~9 CCDs were broken (decam-chatter 7763; two or three nights?).  I _think_ the broken CCDs ended up not coming through the CP---but we should check.

**Comment by moustakas** [comment]
OK, this is fine.  The code is currently agnostic about how many CCDs exist in a given image.  I was thinking of including some additional sanity checks early in the code before anything happens, but counting the number of CCDs is clearly not a good check.

**Comment by djschlegel** [comment]
There was also the run where we lost something like 9 additional CCDs on DECam for a night.

**Comment by djschlegel** [comment]
Closing and moving this issue to the legacypipe product https://github.com/legacysurvey/legacypipe/issues/331
