### ISSUE TITLE
fix failing Travis tests

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacyzpts#38]
Travis tests have been failing probably since Kaylan got his PhD.  Track down the issue(s) and fix.

**Comment by dstndstn** [comment]
Some of this is the tests (which only use the aperture zeropoints anyway) demanding strict equality with Arjun's IDL zeropoints.  I'm going to guess we need to look carefully at designing a new test suite.

Also, Travis was recently acquired and they fired a bunch of people, so I prefer circleci these days.  Legacypipe already has a working circleci build.

**Comment by djschlegel** [comment]
Closing this issue.  Re-open on the legacypipe product if relevant.
