### ISSUE TITLE
DR7: Swap in Eddie's new PS1 - DECam color transformations

### ISSUE THREAD

**Issue by kaylanb** [legacysurvey/legacyzpts#4]
See 
[decam-chatter 4783] DECam grizY color transformations

**Comment by moustakas** [comment]
@mlandriau Do you know off-hand if this was ever addressed?  Thanks.

**Comment by mlandriau** [comment]
I added the new colour terms for Mosaic and 90prime last fall.  Someone else took care of it for DECam before DR7.
