### ISSUE TITLE
blow away single-CCD splinesky and psfex files after merged file is created

### ISSUE THREAD

**Issue by moustakas** [legacysurvey/legacyzpts#40]
The code in PR #39 demands that a splinesky-merged and psfex-merged file exists and is valid before continuing on to compute zeropoints, but we've conservatively chosen to keep the individual CCD files around for now.

Post-DR8, we should just blow these away immediately after the merged file is created (for a given image).

**Comment by djschlegel** [comment]
Close and move over to the legacypipe product https://github.com/legacysurvey/legacypipe/issues/332
