### ISSUE TITLE
Cosmic ray masking on many BASS exposures masks many stars

### ISSUE THREAD

**Issue by schlafly** [legacysurvey/legacyzpts#45]
Many BASS exposures mark many stars as cosmic rays.  We need to think about reprocessing these files or something.  This file
https://faun.rc.fas.harvard.edu/eschlafly/ls/bokflaggedfraction.fits
has the fraction of objects flagged for each Bok exposure.

**Comment by djschlegel** [comment]
Move to legacypipe https://github.com/legacysurvey/legacypipe/issues/334
