### ISSUE TITLE
Reprocess ooi/ood/oow images for cases where we currently have mismatches

### ISSUE THREAD

**Issue by schlafly** [legacysurvey/legacyzpts#46]
For a handful (10s) of exposures, we have different PLVERs of the different image/weight/mask files.  For the DR8 file list, I excluded these exposures from the file list.  We need to reprocess these with a common version of the pipeline if we want to incorporate these images into DR9.

**Comment by djschlegel** [comment]
This issue has been moved over to the legacypipe product https://github.com/legacysurvey/legacypipe/issues/335
