### ISSUE TITLE
Add corrupt files to bad_expid list?

### ISSUE THREAD

**Issue by schlafly** [legacysurvey/legacyzpts#48]
There are a few corrupt files in our various imaging directories.  Depending on how severe the corruption is, these files either pass or do not pass the file list construction stage.  We need to either add these files to the bad_expid file and then check the bad_expid file at file list construction time, or find some other mechanism to remove these files from the file list.

We might like to remove them from the directory structure, but we don't want to redownload them in the future in that case.

We need to look more into whether the files are corrupt at source or just our copies are corrupt.

Currently the bad_expid file is not used to remove files from the file list.  If we changed that, we would not have a chance to recover potentially okay (just shallow) exposures from the bad_expid list; it would be as if these files never existed.

**Comment by djschlegel** [comment]
Move to legacypipe product https://github.com/legacysurvey/legacypipe/issues/336
