### ISSUE TITLE
Clean up imaging data directory structure?

### ISSUE THREAD

**Issue by schlafly** [legacysurvey/legacyzpts#49]
Currently the directory structure in which we store all of our images is not extremely simple.  The DECam file lists are currently built out of:
CPDES82/ 
DECam_CP/
NonDECaLS/
NonDECaLS-DR8/
NonDECaLS-DR8-iY/
DECam_Reprocessed/
The MzLS file lists are built out of
MzLS_CP/
NonMzLS/
and the Bok lists are built out of
BOK_CP/
BOK_TEST/
It's not clear to me that all of these different directories are helping us very much.

Worse, the contents of these directories can be varied... they include corrupt files, stacked files, files with zero second exposure times, files with weird filters, files taken with the sun up, files taken with processing types other than the standard ooi/ood/oow that we usually use.  Maybe that's something we just want to deal with, but it makes understanding these directories more challenging.  It would be good to clean these so that they contained fewer "weird" exposures.

**Comment by djschlegel** [comment]
Move to the legacypipe product https://github.com/legacysurvey/legacypipe/issues/337
