### ISSUE TITLE
Reject BASS data from 2016-03-19 (MJD 57467) as out-of-focus

### ISSUE THREAD

**Issue by djschlegel** [legacysurvey/legacyzpts#53]
The BASS data from 2016-03-19 (MJD 57467) is out-of-focus (partial donuts) for the whole night.  We reject most or all of the exposures based upon the quadrature sum of RARMS,DECRMS being larger than 0.2 arcsec.  Otherwise, the data would have been good as the intrinsic seeing was probably good and the zero-points indicate it was photometric.

<img width="569" alt="Screen Shot 2019-03-25 at 9 44 25 PM" src="https://user-images.githubusercontent.com/7918018/54972590-7e332a00-4f49-11e9-9fb8-4d336e28b8de.png">

**Comment by moustakas** [comment]
@dstndstn Where's the best place to implement this cut?  We have a ccd_cuts bit for `early_decam` data, but we probably don't want a cut just for this night of data.  Or do we?

**Comment by moustakas** [comment]
Included in the bad exposure list in https://github.com/legacysurvey/legacypipe/commit/0364eb6147b9074970218750140e3c28ace25ebe.
