### ISSUE TITLE
Close pairs of sources with separations much less than 1 arcsec

### ISSUE THREAD

**Issue by djschlegel** [legacysurvey/legacyzpts#56]
In dr8b, 0.33% of all sources are in close pairs (or multiples) closer than 1.0 arcsec, 0.24% are in pairs closer than 0.5 arcsec, 0.21% closer than 0.25 arcsec, and 0.14% closer than 0.1 arcsec.

Most of these are PSF/PSF or PSF/REX pairs and have comparable fluxes.  I don't know for certain, but suspect these are not really close pairs, especially since we wouldn't  be sensitive to pairs closer than 0.1 arcsec.

Tabulated below is a sampling of such pairs closer than 0.1 arcsec.  I've only looked in the DECam data:

RA             DEC      TYPE1 TYPE2 RMAG1 RMAG2
   0.0907  -0.1292 PSF  PSF  25.00 15.40
   0.0189  -0.5990 REX  PSF  18.24 14.28
   0.2334  -0.5697 PSF  PSF  16.10 16.64
   0.1511  -0.7473 REX  PSF  16.50 15.35
   0.1064  -0.6984 REX  PSF  18.72 14.95
   0.0394  -0.6782 REX  PSF  25.00 15.26
   0.1656  -0.6573 PSF  PSF  18.21 16.20
   0.0482  -1.0133 REX  PSF  17.73 14.66
   0.2164  -0.9530 REX  PSF  19.40 15.07
   0.1180  -1.2142 PSF  PSF  16.62 15.63
   0.0326  -0.0406 PSF  REX  19.50 15.09
   0.1930   0.0653 PSF  COMP 18.47 15.82
   0.0242   0.2906 REX  PSF  17.37 14.83
   0.2360   0.4074 REX  PSF  16.08 14.84
   0.0024   0.4249 PSF  PSF  16.71 15.71
   0.2383   1.0157 PSF  PSF  17.19 16.59
   0.2254   1.0371 REX  PSF  17.11 15.27

**Comment by dstndstn** [comment]
Could you please move this ticket to legacy*pipe*?

**Comment by djschlegel** [comment]
Duplicate of issue #300 against legacypipe
